CREATE TABLE Patients(
	PID INTEGER PRIMARY KEY AUTOINCREMENT,
	P_First VARCHAR2(100) NOT NULL,
	P_Last VARCHAR2(100) NOT NULL
);

CREATE TABLE Collections(
	CID INTEGER PRIMARY KEY AUTOINCREMENT,
	C_Name VARCHAR2(100) NOT NULL,
        Study VARCHAR2(100) NOT NULL,
	PID INTEGER NOT NULL,
	FOREIGN KEY (PID) REFERENCES Patients
);

CREATE TABLE Images(
	IID VARCHAR2(100),
	CID INTEGER NOT NULL,
	IND NUMBER NOT NULL,
	PRIMARY KEY (IID),
	FOREIGN KEY (CID) REFERENCES Collections
);
