CREATE TABLE Patients(
	PID NUMBER,
	P_First VARCHAR2(100) NOT NULL,
	P_Last VARCHAR2(100) NOT NULL,
	PRIMARY KEY (PID)
);

CREATE TABLE Collections(
	CID NUMBER,
	C_Name VARCHAR2(100) NOT NULL,
	PID NUMBER NOT NULL,
	PRIMARY KEY (CID),
	FOREIGN KEY (PID) REFERENCES ON Patients
);

CREATE TABLE Images(
	IID VARCHAR2(100),
	CID NUMBER NOT NULL,
	Index INTEGER NOT NULL,
	PRIMARY KEY (IID),
	FOREIGN KEY (CID) REFERENCES ON Collections
);

CREATE SEQUENCE PID_GEN
START WITH 1
INCREMENT BY 1;

CREATE SEQUENCE CID_GEN
START WITH 1
INCREMENT BY 1;

CREATE TRIGGER patient_trigger
	BEFORE INSERT ON Patients
	FOR EACH ROW
	BEGIN
		SELECT PID_GEN.NEXTVAL INTO :NEW.PID FROM DUAL;
	END;
/

CREATE TRIGGER collection_trigger
	BEFORE INSERT ON Collections
	FOR EACH ROW
	BEGIN
		SELECT CID_GEN.NEXTVAL INTO :NEW.CID FROM DUAL;
	END;
/
